"""Persian simple constant definitions."""

PERSIAN_PE: str = "\u067E"
""" Persian Pe Letter """
PERSIAN_CE: str = "\u0686"
""" Persian Ce Letter """
PERSIAN_ZE: str = "\u0698"
""" Persian Ze Letter """
PERSIAN_KAF: str = "\u06A9"
""" Persian Kaf Letter """
PERSIAN_GAF: str = "\u06AF"
""" Persian Gaf Letter """
PERSIAN_YE: str = "\u06CC"
""" Persian Ye Letter """
PERSIAN_EYE: str = "\u06C0"
""" Persian Eye Letter """

PERSIAN_ZERO: str = "\u06F0"
""" Persian Zero Digit """
PERSIAN_ONE: str = "\u06F1"
""" Persian One Digit """
PERSIAN_TWO: str = "\u06F2"
""" Persian Two Digit """
PERSIAN_THREE: str = "\u06F3"
""" Persian Three Digit """
PERSIAN_FOUR: str = "\u06F4"
""" Persian Four Digit """
PERSIAN_FIVE: str = "\u06F5"
""" Persian Five Digit """
PERSIAN_SIX: str = "\u06F6"
""" Persian Six Digit """
PERSIAN_SEVEN: str = "\u06F7"
""" Persian Seven Digit """
PERSIAN_EIGHT: str = "\u06F8"
""" Persian Eight Digit """
PERSIAN_NINE: str = "\u06F9"
""" Persian Nine Digit """
