coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project:
      default:
        enabled: yes
        target: 75%
        threshold: 4%
    patch:
      default:
        enabled: off
