"""English simple constant definitions."""

A: str = "A"
""" Latin Capital letter A """
B: str = "B"
""" Latin Capital letter B """
C: str = "C"
""" Latin Capital letter C """
D: str = "D"
""" Latin Capital letter D """
E: str = "E"
""" Latin Capital letter E """
F: str = "F"
""" Latin Capital letter F """
G: str = "G"
""" Latin Capital letter G """
H: str = "H"
""" Latin Capital letter H """
I: str = "I"
""" Latin Capital letter I """
J: str = "J"
""" Latin Capital letter J """
K: str = "K"
""" Latin Capital letter K """
L: str = "L"
""" Latin Capital letter L """
M: str = "M"
""" Latin Capital letter M """
N: str = "N"
""" Latin Capital letter N """
O: str = "O"
""" Latin Capital letter O """
P: str = "P"
""" Latin Capital letter P """
Q: str = "Q"
""" Latin Capital letter Q """
R: str = "R"
""" Latin Capital letter R """
S: str = "S"
""" Latin Capital letter S """
T: str = "T"
""" Latin Capital letter T """
U: str = "U"
""" Latin Capital letter U """
V: str = "V"
""" Latin Capital letter V """
W: str = "W"
""" Latin Capital letter W """
X: str = "X"
""" Latin Capital letter X """
Y: str = "Y"
""" Latin Capital letter Y """
Z: str = "Z"
""" Latin Capital letter Z """

SMALL_A: str = "a"
""" Latin Small letter A """
SMALL_B: str = "b"
""" Latin Small letter B """
SMALL_C: str = "c"
""" Latin Small letter C """
SMALL_D: str = "d"
""" Latin Small letter D """
SMALL_E: str = "e"
""" Latin Small letter E """
SMALL_F: str = "f"
""" Latin Small letter F """
SMALL_G: str = "g"
""" Latin Small letter G """
SMALL_H: str = "h"
""" Latin Small letter H """
SMALL_I: str = "i"
""" Latin Small letter I """
SMALL_J: str = "j"
""" Latin Small letter J """
SMALL_K: str = "k"
""" Latin Small letter K """
SMALL_L: str = "l"
""" Latin Small letter L """
SMALL_M: str = "m"
""" Latin Small letter M """
SMALL_N: str = "n"
""" Latin Small letter N """
SMALL_O: str = "o"
""" Latin Small letter O """
SMALL_P: str = "p"
""" Latin Small letter P """
SMALL_Q: str = "q"
""" Latin Small letter Q """
SMALL_R: str = "r"
""" Latin Small letter R """
SMALL_S: str = "s"
""" Latin Small letter S """
SMALL_T: str = "t"
""" Latin Small letter T """
SMALL_U: str = "u"
""" Latin Small letter U """
SMALL_V: str = "v"
""" Latin Small letter V """
SMALL_W: str = "w"
""" Latin Small letter W """
SMALL_X: str = "x"
""" Latin Small letter X """
SMALL_Y: str = "y"
""" Latin Small letter Y """
SMALL_Z: str = "z"
""" Latin Small letter Z """

# Digits
ZERO: str = "0"
""" Digit Zero """
ONE: str = "1"
"""	Digit One """
TWO: str = "2"
"""	Digit Two """
THREE: str = "3"
"""	Digit Three """
FOUR: str = "4"
"""	Digit Four """
FIVE: str = "5"
"""	Digit Five """
SIX: str = "6"
"""	Digit Six """
SEVEN: str = "7"
"""	Digit Seven """
EIGHT: str = "8"
"""	Digit Eight """
NINE: str = "9"
"""	Digit Nine """

# Punctuation
EXCLAMATION_MARK: str = "!"
QUOTATION_MARK: str = '"'
NUMBER_SIGN: str = "#"
HASHTAG: str = NUMBER_SIGN
DOLLAR_SIGN: str = "$"
PERCENT_SIGN: str = "%"
AND_SIGN: str = "&"
AMPERSAND: str = AND_SIGN
APOSTROPHE: str = "'"
LEFT_PARENTHESIS: str = "("
RIGHT_PARENTHESIS: str = ")"
ASTERISK: str = "*"
PLUS_SIGN: str = "+"
COMMA: str = ","
MINUS_SIGN: str = "-"
HYPHEN_SIGN: str = MINUS_SIGN
DOT: str = "."
FULL_STOP: str = DOT
SLASH: str = "/"
COLON: str = ":"
SEMICOLON: str = ";"
LESSTHAN_SIGN: str = "<"
EQUAL_SIGN: str = "="
GREATERTHAN_SIGN: str = ">"
QUESTION_MARK: str = "?"
AT_SIGN: str = "@"
LEFT_BRACKET: str = "["
BACKSLASH: str = "\\"
RIGHT_BRACKET: str = "]"
EXPONENT_SIGN: str = "^"
CIRCUMFLEX_ACCENT: str = EXPONENT_SIGN
UNDERSCORE: str = "_"
LOWLINE: str = UNDERSCORE
GRAVE_ACCENT: str = "`"
LEFTCURLY_BRACKET: str = "{"
VERTICAL_BAR: str = "|"
RIGHTCURLY_BRACKET: str = "}"
TILDE: str = "~"
