"""Constant definitions."""

# Arabic letters
ALEF: str = "\u0627"
""" Arabic Letter Alef """
BEH: str = "\u0628"
""" Arabic Letter Beh """
TEH: str = "\u062A"
""" Arabic Letter Teh """
THEH: str = "\u062B"
""" Arabic Letter Theh """
JEEM: str = "\u062C"
""" Arabic Letter Jeem """
HAH: str = "\u062D"
""" Arabic Letter Hah """
KHAH: str = "\u062E"
""" Arabic Letter Khah """
DAL: str = "\u062F"
""" Arabic Letter Dal """
THAL: str = "\u0630"
""" Arabic Letter Thal """
REH: str = "\u0631"
""" Arabic Letter Reh """
ZAIN: str = "\u0632"
""" Arabic Letter Zain """
SEEN: str = "\u0633"
""" Arabic Letter Seen """
SHEEN: str = "\u0634"
""" Arabic Letter Sheen """
SAD: str = "\u0635"
""" Arabic Letter Sad """
DAD: str = "\u0636"
""" Arabic Letter Dad """
TAH: str = "\u0637"
""" Arabic Letter Tah """
ZAH: str = "\u0638"
""" Arabic Letter Zah """
AIN: str = "\u0639"
""" Arabic Letter Ain """
GHAIN: str = "\u063A"
""" Arabic Letter Ghain """
FEH: str = "\u0641"
""" Arabic Letter Feh """
QAF: str = "\u0642"
""" Arabic Letter Qaf """
KAF: str = "\u0643"
""" Arabic Letter Kaf """
LAM: str = "\u0644"
""" Arabic Letter Lam """
MEEM: str = "\u0645"
""" Arabic Letter Meem """
NOON: str = "\u0646"
""" Arabic Letter Noon """
HEH: str = "\u0647"
""" Arabic Letter Heh """
WAW: str = "\u0648"
""" Arabic Letter Waw """
YEH: str = "\u064A"
""" Arabic Letter Yeh """
ALEF_MAKSURA: str = "\u0649"
""" Arabic Letter Alef Maksura """
TEH_MARBUTA: str = "\u0629"
""" Arabic Letter Teh Marbuta """
ALEF_MADDA_ABOVE: str = "\u0622"
""" Arabic Letter Alef With Madda Above """
ALEF_HAMZA_ABOVE: str = "\u0623"
""" Arabic Letter Alef With Hamza Above """
ALEF_HAMZA_BELOW: str = "\u0625"
""" Arabic Letter Alef With Hamza Below """
HAMZA: str = "\u0621"
""" Arabic Letter Hamza """
HAMZA_WAW: str = "\u0624"
""" Arabic Letter Waw With Hamza Above """
HAMZA_YA: str = "\u0626"
""" Arabic Letter Yeh With Hamza Above """
TATWEEL: str = "\u0640"
""" Arabic Tatweel """
KASHIDA: str = TATWEEL
""" Alias for Arabic Tatweel """

# LAM ALEF
LAM_ALEF: str = "\ufefb"
""" Arabic Ligature Lam with Alef Isolated Form """
LAM_ALEF_HAMZA_ABOVE: str = "\ufef7"
""" Arabic Ligature Lam with Alef with Hamza Above Isolated Form """
LAM_ALEF_HAMZA_BELOW: str = "\ufef9"
""" Arabic Ligature Lam with Alef with Hamza Below Isolated Form """
LAM_ALEF_MADDA_ABOVE: str = "\ufef5"
""" Arabic Ligature Lam with Alef with Madda Above Isolated Form """

# Diacritics (Harakat)
FATHATAN: str = "\u064B"
""" Arabic Fathatan """
DAMMATAN: str = "\u064C"
""" Arabic Dammatan """
KASRATAN: str = "\u064D"
""" Arabic Kasratan """
FATHA: str = "\u064E"
""" Arabic Fatha """
DAMMA: str = "\u064F"
""" Arabic Damma """
KASRA: str = "\u0650"
""" Arabic Kasra """
SHADDA: str = "\u0651"
""" Arabic Shadda """
SUKUN: str = "\u0652"
""" Arabic Sukun """

# Arabic Numbers
ZERO: str = "\u0660"
""" Arabic-Indic Digit Zero """
ONE: str = "\u0661"
""" Arabic-Indic Digit One """
TWO: str = "\u0662"
""" Arabic-Indic Digit Two """
THREE: str = "\u0663"
""" Arabic-Indic Digit Three """
FOUR: str = "\u0664"
""" Arabic-Indic Digit Four """
FIVE: str = "\u0665"
""" Arabic-Indic Digit Five """
SIX: str = "\u0666"
""" Arabic-Indic Digit Six """
SEVEN: str = "\u0667"
""" Arabic-Indic Digit Seven """
EIGHT: str = "\u0668"
""" Arabic-Indic Digit Eight """
NINE: str = "\u0669"
""" Arabic-Indic Digit Nine """

# Arabic Punctuation
COMMA: str = "\u060C"
""" Arabic Comma """
SEMICOLON: str = "\u061B"
""" Arabic Semicolon """
QUESTION_MARK: str = "\u061F"
""" Arabic Question Mark """
TRIPLE_DOT: str = "\u061E"
""" Arabic Triple Dot Punctuation Mark """
STAR: str = "\u066D"
""" Arabic Five Pointed Star """
FULL_STOP: str = "\u066D"
""" Arabic Full Stop """
DATE_SEPARATOR: str = "\u060D"
""" Arabic Date Separator """
END_OF_AYAH: str = "\u06DD"
""" Arabic End Of Ayah """
MISRA_SIGN: str = "\u060F"
""" Arabic Sign Misra """
POETIC_VERSE_SIGN: str = "\u060E"
""" Arabic Poetic Verse Sign """
SAJDAH: str = "\u06E9"
""" Arabic Place Of Sajdah """
HIZB_START: str = "\u06DE"
""" Arabic Start Of Rub El Hizb """
ORNATE_LEFT_PARENTHESIS: str = "\uFD3E"
""" Arabic Ornate Left Parenthesis """
ORNATE_RIGHT_PARENTHESIS: str = "\uFD3F"
""" Arabic Ornate Right Parenthesis """

# Word Ligatures
