from maha.constants import PATTERN_SPACE, PATTERN_SPACE_OR_NONE
from maha.rexy import Expression, non_capturing_group

from ..constants import ALL_ALEF, SUM_SUFFIX, TWO_SUFFIX
from ..interfaces import ValueExpression

TEN_SUFFIX = Expression(f"{PATTERN_SPACE_OR_NONE}[تط]?[اع]?شر?[ةه]?")
TEH_OPTIONAL_SUFFIX = Expression("[ةه]?")

PREFIX_OF_THREE = Expression("[ثت]لا[ثت]")
PREFIX_OF_FOUR = Expression("[أا]ربع")
PREFIX_OF_FIVE = Expression("خمس")
PREFIX_OF_SIX = Expression("ست")
PREFIX_OF_SEVEN = Expression("سبع")
PREFIX_OF_EIGHT = Expression("[تث]ما?ني?")
PREFIX_OF_NINE = Expression("تسع")
PREFIX_OF_TEN = Expression("عشر")

EXPRESSION_OF_ZERO = ValueExpression(0, "صفر")
EXPRESSION_OF_ONE = ValueExpression(1, "وا?حد" + TEH_OPTIONAL_SUFFIX)
EXPRESSION_OF_TWO = ValueExpression(2, "[إا][ثت]نت?[اي]ن")
EXPRESSION_OF_THREE = ValueExpression(3, PREFIX_OF_THREE + TEH_OPTIONAL_SUFFIX)
EXPRESSION_OF_FOUR = ValueExpression(4, PREFIX_OF_FOUR + TEH_OPTIONAL_SUFFIX)
EXPRESSION_OF_FIVE = ValueExpression(5, PREFIX_OF_FIVE + TEH_OPTIONAL_SUFFIX)
EXPRESSION_OF_SIX = ValueExpression(6, PREFIX_OF_SIX + TEH_OPTIONAL_SUFFIX)
EXPRESSION_OF_SEVEN = ValueExpression(7, PREFIX_OF_SEVEN + TEH_OPTIONAL_SUFFIX)
EXPRESSION_OF_EIGHT = ValueExpression(8, PREFIX_OF_EIGHT + TEH_OPTIONAL_SUFFIX)
EXPRESSION_OF_NINE = ValueExpression(9, PREFIX_OF_NINE + TEH_OPTIONAL_SUFFIX)
EXPRESSION_OF_TEN = ValueExpression(10, PREFIX_OF_TEN + TEH_OPTIONAL_SUFFIX)
EXPRESSION_OF_ELEVEN = ValueExpression(11, f"{ALL_ALEF}?حد[اى]?" + TEN_SUFFIX)
EXPRESSION_OF_TWELVE = ValueExpression(
    12,
    non_capturing_group(
        f"{ALL_ALEF}[طت]نا?" + TEN_SUFFIX, f"{ALL_ALEF}[ثت]نت?[اىي]ن?" + TEN_SUFFIX
    ),
)
EXPRESSION_OF_THIRTEEN = ValueExpression(
    13, "[ثت]لا?[ثت]" + TEH_OPTIONAL_SUFFIX + TEN_SUFFIX
)
EXPRESSION_OF_FOURTEEN = ValueExpression(14, EXPRESSION_OF_FOUR + TEN_SUFFIX)
EXPRESSION_OF_FIFTEEN = ValueExpression(15, EXPRESSION_OF_FIVE + TEN_SUFFIX)
EXPRESSION_OF_SIXTEEN = ValueExpression(16, EXPRESSION_OF_SIX + TEN_SUFFIX)
EXPRESSION_OF_SEVENTEEN = ValueExpression(17, EXPRESSION_OF_SEVEN + TEN_SUFFIX)
EXPRESSION_OF_EIGHTEEN = ValueExpression(
    18, "[تث]ما?ني?" + TEH_OPTIONAL_SUFFIX + TEN_SUFFIX
)
EXPRESSION_OF_NINETEEN = ValueExpression(19, EXPRESSION_OF_NINE + TEN_SUFFIX)
EXPRESSION_OF_TWENTY = ValueExpression(20, PREFIX_OF_TEN + SUM_SUFFIX)
EXPRESSION_OF_THIRTY = ValueExpression(30, PREFIX_OF_THREE + SUM_SUFFIX)
EXPRESSION_OF_FORTY = ValueExpression(40, PREFIX_OF_FOUR + SUM_SUFFIX)
EXPRESSION_OF_FIFTY = ValueExpression(50, PREFIX_OF_FIVE + SUM_SUFFIX)
EXPRESSION_OF_SIXTY = ValueExpression(60, PREFIX_OF_SIX + SUM_SUFFIX)
EXPRESSION_OF_SEVENTY = ValueExpression(70, PREFIX_OF_SEVEN + SUM_SUFFIX)
EXPRESSION_OF_EIGHTY = ValueExpression(80, PREFIX_OF_EIGHT + SUM_SUFFIX)
EXPRESSION_OF_NINETY = ValueExpression(90, PREFIX_OF_NINE + SUM_SUFFIX)


EXPRESSION_OF_HUNDRED = ValueExpression(100, "ما?[يئ][ةه]")
EXPRESSION_OF_TWO_HUNDREDS = ValueExpression(200, "م[يئ]ت" + TWO_SUFFIX)
EXPRESSION_OF_THREE_HUNDREDS = ValueExpression(
    300, EXPRESSION_OF_THREE + PATTERN_SPACE_OR_NONE + EXPRESSION_OF_HUNDRED
)
EXPRESSION_OF_FOUR_HUNDREDS = ValueExpression(
    400, EXPRESSION_OF_FOUR + PATTERN_SPACE_OR_NONE + EXPRESSION_OF_HUNDRED
)
EXPRESSION_OF_FIVE_HUNDREDS = ValueExpression(
    500, EXPRESSION_OF_FIVE + PATTERN_SPACE_OR_NONE + EXPRESSION_OF_HUNDRED
)
EXPRESSION_OF_SIX_HUNDREDS = ValueExpression(
    600, EXPRESSION_OF_SIX + PATTERN_SPACE_OR_NONE + EXPRESSION_OF_HUNDRED
)
EXPRESSION_OF_SEVEN_HUNDREDS = ValueExpression(
    700, EXPRESSION_OF_SEVEN + PATTERN_SPACE_OR_NONE + EXPRESSION_OF_HUNDRED
)
EXPRESSION_OF_EIGHT_HUNDREDS = ValueExpression(
    800, EXPRESSION_OF_EIGHT + PATTERN_SPACE_OR_NONE + EXPRESSION_OF_HUNDRED
)
EXPRESSION_OF_NINE_HUNDREDS = ValueExpression(
    900, EXPRESSION_OF_NINE + PATTERN_SPACE_OR_NONE + EXPRESSION_OF_HUNDRED
)
EXPRESSION_OF_HUNDREDS = ValueExpression(100, "م[يئ]ا?ت")

EXPRESSION_OF_THOUSAND = ValueExpression(1000, "[أا]لف")
EXPRESSION_OF_TWO_THOUSANDS = ValueExpression(2000, EXPRESSION_OF_THOUSAND + TWO_SUFFIX)
EXPRESSION_OF_THOUSANDS = ValueExpression(
    1000,
    non_capturing_group(
        f"{ALL_ALEF}ل[او]ف",
        f"{ALL_ALEF}لفات",
    ),
)
EXPRESSION_OF_MILLION = ValueExpression(1000000, "مليون")
EXPRESSION_OF_TWO_MILLIONS = ValueExpression(
    2000000, EXPRESSION_OF_MILLION + TWO_SUFFIX
)
EXPRESSION_OF_MILLIONS = ValueExpression(1000000, "ملايين")
EXPRESSION_OF_BILLION = ValueExpression(
    1000000000, non_capturing_group("بليون", "مليار")
)
EXPRESSION_OF_TWO_BILLIONS = ValueExpression(
    2000000000, EXPRESSION_OF_BILLION + TWO_SUFFIX
)
EXPRESSION_OF_BILLIONS = ValueExpression(
    1000000000, non_capturing_group("بلايين", "مليارات")
)
EXPRESSION_OF_TRILLION = ValueExpression(1000000000000, "تري?ليون")
EXPRESSION_OF_TWO_TRILLIONS = ValueExpression(
    2000000000000, EXPRESSION_OF_TRILLION + TEN_SUFFIX
)
EXPRESSION_OF_TRILLIONS = ValueExpression(1000000000000, EXPRESSION_OF_TRILLION + "ات")

EXPRESSION_OF_FASILA = Expression(
    PATTERN_SPACE + "فاصل" + TEH_OPTIONAL_SUFFIX + PATTERN_SPACE
)
