from maha.constants import ALEF_VARIATIONS, PATTERN_SPACE_OR_NONE

from ..constants import SUM_SUFFIX, TWO_SUFFIX
from ..helper import get_non_capturing_group

ALL_ALEF = "".join(ALEF_VARIATIONS)
TEN_SUFFIX = f"{PATTERN_SPACE_OR_NONE}[تط]?[اع]?شر?[ةه]?"
TEH_OPTIONAL_SUFFIX = "[ةه]?"

PREFIX_OF_THREE = "[ثت]لا[ثت]"
PREFIX_OF_FOUR = "[أا]ربع"
PREFIX_OF_FIVE = "خمس"
PREFIX_OF_SIX = "ست"
PREFIX_OF_SEVEN = "سبع"
PREFIX_OF_EIGHT = "[تث]ما?ني"
PREFIX_OF_NINE = "تسع"
PREFIX_OF_TEN = "عشر"

NAME_OF_ZERO = "صفر"
NAME_OF_ONE = "وا?حد" + TEH_OPTIONAL_SUFFIX
NAME_OF_TWO = "[إا][ثت]نت?[اي]ن"
NAME_OF_THREE = PREFIX_OF_THREE + TEH_OPTIONAL_SUFFIX
NAME_OF_FOUR = PREFIX_OF_FOUR + TEH_OPTIONAL_SUFFIX
NAME_OF_FIVE = PREFIX_OF_FIVE + TEH_OPTIONAL_SUFFIX
NAME_OF_SIX = PREFIX_OF_SIX + TEH_OPTIONAL_SUFFIX
NAME_OF_SEVEN = PREFIX_OF_SEVEN + TEH_OPTIONAL_SUFFIX
NAME_OF_EIGHT = PREFIX_OF_EIGHT + TEH_OPTIONAL_SUFFIX
NAME_OF_NINE = PREFIX_OF_NINE + TEH_OPTIONAL_SUFFIX
NAME_OF_TEN = PREFIX_OF_TEN + TEH_OPTIONAL_SUFFIX
NAME_OF_ELEVEN = f"[{ALL_ALEF}]?حد[اى]?" + TEN_SUFFIX
NAME_OF_TWELVE = get_non_capturing_group(
    f"[{ALL_ALEF}][طت]نا?" + TEN_SUFFIX, f"[{ALL_ALEF}][ثت]نت?[اىي]ن?" + TEN_SUFFIX
)
NAME_OF_THIRTEEN = "[ثت]لا?[ثت]" + TEH_OPTIONAL_SUFFIX + TEN_SUFFIX
NAME_OF_FOURTEEN = NAME_OF_FOUR + TEN_SUFFIX
NAME_OF_FIFTEEN = NAME_OF_FIVE + TEN_SUFFIX
NAME_OF_SIXTEEN = NAME_OF_SIX + TEN_SUFFIX
NAME_OF_SEVENTEEN = NAME_OF_SEVEN + TEN_SUFFIX
NAME_OF_EIGHTEEN = "[تث]ما?ني?" + TEH_OPTIONAL_SUFFIX + TEN_SUFFIX
NAME_OF_NINETEEN = NAME_OF_NINE + TEN_SUFFIX
NAME_OF_TWENTY = PREFIX_OF_TEN + SUM_SUFFIX
NAME_OF_EIGHTY = "[تث]ما?ن" + SUM_SUFFIX

NAME_OF_HUNDRED = "ما?[يئ][ةه]"
NAME_OF_TWO_HUNDREDS = "م[يئ]ت" + TWO_SUFFIX
NAME_OF_HUNDREDS = "م[يئ]ا?ت"
NAME_OF_THOUSAND = "[أا]لف"
NAME_OF_TWO_THOUSANDS = NAME_OF_THOUSAND + TWO_SUFFIX
NAME_OF_THOUSANDS = get_non_capturing_group(f"[{ALL_ALEF}]ل[او]ف", f"[{ALL_ALEF}]لفات")
NAME_OF_MILLION = "مليون"
NAME_OF_TWO_MILLIONS = NAME_OF_MILLION + TWO_SUFFIX
NAME_OF_MILLIONS = "ملايين"
NAME_OF_BILLION = get_non_capturing_group("بليون", "مليار")
NAME_OF_TWO_BILLIONS = NAME_OF_BILLION + TWO_SUFFIX
NAME_OF_BILLIONS = get_non_capturing_group("بلايين", "مليارات")
NAME_OF_TRILLION = "تري?ليون"
NAME_OF_TWO_TRILLIONS = NAME_OF_TRILLION + TEN_SUFFIX
NAME_OF_TRILLIONS = NAME_OF_TRILLION + "ات"

NAME_OF_FASILA = "فاصل" + TEH_OPTIONAL_SUFFIX
