from maha.constants import PATTERN_SPACE, PATTERN_SPACE_OR_NONE
from maha.rexy import get_non_capturing_group

from ..constants import ALL_ALEF, SUM_SUFFIX, TWO_SUFFIX
from ..interfaces import Expression, ValueExpression

TEN_SUFFIX = Expression(f"{PATTERN_SPACE_OR_NONE}[تط]?[اع]?شر?[ةه]?")
TEH_OPTIONAL_SUFFIX = Expression("[ةه]?")

PREFIX_OF_THREE = Expression("[ثت]لا[ثت]")
PREFIX_OF_FOUR = Expression("[أا]ربع")
PREFIX_OF_FIVE = Expression("خمس")
PREFIX_OF_SIX = Expression("ست")
PREFIX_OF_SEVEN = Expression("سبع")
PREFIX_OF_EIGHT = Expression("[تث]ما?ني?")
PREFIX_OF_NINE = Expression("تسع")
PREFIX_OF_TEN = Expression("عشر")

EXPRESSION_OF_ZERO = ValueExpression("صفر", 0)
EXPRESSION_OF_ONE = ValueExpression("وا?حد" + TEH_OPTIONAL_SUFFIX, 1)
EXPRESSION_OF_TWO = ValueExpression("[إا][ثت]نت?[اي]ن", 2)
EXPRESSION_OF_THREE = ValueExpression(PREFIX_OF_THREE + TEH_OPTIONAL_SUFFIX, 3)
EXPRESSION_OF_FOUR = ValueExpression(PREFIX_OF_FOUR + TEH_OPTIONAL_SUFFIX, 4)
EXPRESSION_OF_FIVE = ValueExpression(PREFIX_OF_FIVE + TEH_OPTIONAL_SUFFIX, 5)
EXPRESSION_OF_SIX = ValueExpression(PREFIX_OF_SIX + TEH_OPTIONAL_SUFFIX, 6)
EXPRESSION_OF_SEVEN = ValueExpression(PREFIX_OF_SEVEN + TEH_OPTIONAL_SUFFIX, 7)
EXPRESSION_OF_EIGHT = ValueExpression(PREFIX_OF_EIGHT + TEH_OPTIONAL_SUFFIX, 8)
EXPRESSION_OF_NINE = ValueExpression(PREFIX_OF_NINE + TEH_OPTIONAL_SUFFIX, 9)
EXPRESSION_OF_TEN = ValueExpression(PREFIX_OF_TEN + TEH_OPTIONAL_SUFFIX, 10)
EXPRESSION_OF_ELEVEN = ValueExpression(f"{ALL_ALEF}?حد[اى]?" + TEN_SUFFIX, 11)
EXPRESSION_OF_TWELVE = ValueExpression(
    get_non_capturing_group(
        f"{ALL_ALEF}[طت]نا?" + TEN_SUFFIX, f"{ALL_ALEF}[ثت]نت?[اىي]ن?" + TEN_SUFFIX
    ),
    12,
)
EXPRESSION_OF_THIRTEEN = ValueExpression(
    "[ثت]لا?[ثت]" + TEH_OPTIONAL_SUFFIX + TEN_SUFFIX, 13
)
EXPRESSION_OF_FOURTEEN = ValueExpression(EXPRESSION_OF_FOUR + TEN_SUFFIX, 14)
EXPRESSION_OF_FIFTEEN = ValueExpression(EXPRESSION_OF_FIVE + TEN_SUFFIX, 15)
EXPRESSION_OF_SIXTEEN = ValueExpression(EXPRESSION_OF_SIX + TEN_SUFFIX, 16)
EXPRESSION_OF_SEVENTEEN = ValueExpression(EXPRESSION_OF_SEVEN + TEN_SUFFIX, 17)
EXPRESSION_OF_EIGHTEEN = ValueExpression(
    "[تث]ما?ني?" + TEH_OPTIONAL_SUFFIX + TEN_SUFFIX, 18
)
EXPRESSION_OF_NINETEEN = ValueExpression(EXPRESSION_OF_NINE + TEN_SUFFIX, 19)
EXPRESSION_OF_TWENTY = ValueExpression(PREFIX_OF_TEN + SUM_SUFFIX, 20)
EXPRESSION_OF_THIRTY = ValueExpression(PREFIX_OF_THREE + SUM_SUFFIX, 30)
EXPRESSION_OF_FORTY = ValueExpression(PREFIX_OF_FOUR + SUM_SUFFIX, 40)
EXPRESSION_OF_FIFTY = ValueExpression(PREFIX_OF_FIVE + SUM_SUFFIX, 50)
EXPRESSION_OF_SIXTY = ValueExpression(PREFIX_OF_SIX + SUM_SUFFIX, 60)
EXPRESSION_OF_SEVENTY = ValueExpression(PREFIX_OF_SEVEN + SUM_SUFFIX, 70)
EXPRESSION_OF_EIGHTY = ValueExpression(PREFIX_OF_EIGHT + SUM_SUFFIX, 80)
EXPRESSION_OF_NINETY = ValueExpression(PREFIX_OF_NINE + SUM_SUFFIX, 90)


EXPRESSION_OF_HUNDRED = ValueExpression("ما?[يئ][ةه]", 100)
EXPRESSION_OF_TWO_HUNDREDS = ValueExpression("م[يئ]ت" + TWO_SUFFIX, 200)
EXPRESSION_OF_THREE_HUNDREDS = ValueExpression(
    EXPRESSION_OF_THREE + PATTERN_SPACE_OR_NONE + EXPRESSION_OF_HUNDRED, 300
)
EXPRESSION_OF_FOUR_HUNDREDS = ValueExpression(
    EXPRESSION_OF_FOUR + PATTERN_SPACE_OR_NONE + EXPRESSION_OF_HUNDRED, 400
)
EXPRESSION_OF_FIVE_HUNDREDS = ValueExpression(
    EXPRESSION_OF_FIVE + PATTERN_SPACE_OR_NONE + EXPRESSION_OF_HUNDRED, 500
)
EXPRESSION_OF_SIX_HUNDREDS = ValueExpression(
    EXPRESSION_OF_SIX + PATTERN_SPACE_OR_NONE + EXPRESSION_OF_HUNDRED, 600
)
EXPRESSION_OF_SEVEN_HUNDREDS = ValueExpression(
    EXPRESSION_OF_SEVEN + PATTERN_SPACE_OR_NONE + EXPRESSION_OF_HUNDRED, 700
)
EXPRESSION_OF_EIGHT_HUNDREDS = ValueExpression(
    EXPRESSION_OF_EIGHT + PATTERN_SPACE_OR_NONE + EXPRESSION_OF_HUNDRED, 800
)
EXPRESSION_OF_NINE_HUNDREDS = ValueExpression(
    EXPRESSION_OF_NINE + PATTERN_SPACE_OR_NONE + EXPRESSION_OF_HUNDRED, 900
)
EXPRESSION_OF_HUNDREDS = ValueExpression("م[يئ]ا?ت", 100)

EXPRESSION_OF_THOUSAND = ValueExpression("[أا]لف", 1000)
EXPRESSION_OF_TWO_THOUSANDS = ValueExpression(EXPRESSION_OF_THOUSAND + TWO_SUFFIX, 2000)
EXPRESSION_OF_THOUSANDS = ValueExpression(
    get_non_capturing_group(
        f"{ALL_ALEF}ل[او]ف",
        f"{ALL_ALEF}لفات",
    ),
    1000,
)
EXPRESSION_OF_MILLION = ValueExpression("مليون", 1000000)
EXPRESSION_OF_TWO_MILLIONS = ValueExpression(
    EXPRESSION_OF_MILLION + TWO_SUFFIX, 2000000
)
EXPRESSION_OF_MILLIONS = ValueExpression("ملايين", 1000000)
EXPRESSION_OF_BILLION = ValueExpression(
    get_non_capturing_group("بليون", "مليار"), 1000000000
)
EXPRESSION_OF_TWO_BILLIONS = ValueExpression(
    EXPRESSION_OF_BILLION + TWO_SUFFIX, 2000000000
)
EXPRESSION_OF_BILLIONS = ValueExpression(
    get_non_capturing_group("بلايين", "مليارات"), 1000000000
)
EXPRESSION_OF_TRILLION = ValueExpression("تري?ليون", 1000000000000)
EXPRESSION_OF_TWO_TRILLIONS = ValueExpression(
    EXPRESSION_OF_TRILLION + TEN_SUFFIX, 2000000000000
)
EXPRESSION_OF_TRILLIONS = ValueExpression(EXPRESSION_OF_TRILLION + "ات", 1000000000000)

EXPRESSION_OF_FASILA = Expression(
    PATTERN_SPACE + "فاصل" + TEH_OPTIONAL_SUFFIX + PATTERN_SPACE
)
